apiVersion: apps/v1
kind: Deployment
metadata:
  name: captureorder
spec:
  selector:
      matchLabels:
        app: captureorder
  replicas: 2
  template:
      metadata:
        labels:
            app: captureorder
      spec:
        containers:
        - name: captureorder
          image: kuberneteswp.azurecr.io/captureorder:placeholdertag # replace with your own repository. Due to a bug, leave the :placeholdertag tag in there to allow the pipeline to replace it
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8080
              path: /healthz
          livenessProbe:
            httpGet:
              port: 8080
              path: /healthz
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
          - name: TEAMNAME
            value: 'team-azch' # will be patched at deployment time by value of 'teamName' in the variable group
          - name: MONGOHOST
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: mongoHost
          - name: MONGOUSER
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: mongoUser
          ports:
          - containerPort: 80volumes:
          volumeMounts:
          - name: mongosecret
            flexVolume:
              driver: "azure/kv"
              secretRef:
                name: kvcreds
              options:
                usepodidentity: "false"
                keyvaultname: kubernetes-keyvault-wp
                keyvaultobjectnames: mongo-password # Name of Key Vault secret
                keyvaultobjecttypes: secret
                resourcegroup: kubernetes-rg
                subscriptionid: dcd66cac-104d-45a1-a02e-39066740b01f
                tenantid: 39e3566e-8a95-4890-8a14-b6054c752634
                volumeMounts:
          - name: mongosecret
            mountPath: /kvmnt
            readOnly: true
